services:
  newsboat:
    image: alpine:latest
    stdin_open: true
    tty: true
    volumes:
      - ./local/etc/newsboat:/root/.config/newsboat
      - $XDG_DATA_HOME/newsboat:/root/.local/share/newsboat
    command: |
      sh -c "apk add --no-cache newsboat python3 && newsboat"
